Add README for Jan
justinmohs/pp_analysis pull request #3
Opened 2018-12-19 17:12 UTC by justinmohs

There you go

2018-12-19 17:12 UTC, justinmohs commented
ref #1

2018-12-20 13:28 UTC, stdnmr requested changes
Good to see progress here, but a few small changes are still necessary. Thanks.

2018-12-20 13:28 UTC, stdnmr commented on README.md
> +just run the shell script
Could you please make this a real sentence and mention which shell script.

2018-12-20 13:28 UTC, stdnmr commented on README.md
> +# This is for analysing p+p results from SMASH.
What about: 
```suggestion
# pp Analysis

This is repository for analyzing p+p results from SMASH.
```

2018-12-21 10:13 UTC, stdnmr commented
Did the changes myself, although I could not figure out, which shell script one has to run precisely.

2018-12-21 10:13 UTC, merged